---
type: docker
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: install
  image: node:14
  commands: ["npm install"]

- name: standard
  image: node:14
  commands: ["npm run lint -s"]

- name: test-node-14
  image: node:14
  commands: ["npm run test:ci -s"]

- name: test-node-16
  image: node:16
  commands: ["npm run test:ci -s"]

- name: publish
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
---
kind: signature
hmac: 5585a3ecd5f35ecd04edf44d181e77d271400608a52d1f7284c8a4af598fc6b4

...
