---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: install
  image: node:8-alpine
  commands: ["npm install"]

- name: standard
  image: node:8-alpine
  commands: ["npm run lint -s"]

- name: test-node-8
  image: node:8-alpine
  commands: ["npm run test:ci -s"]

- name: publish
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
---
kind: signature
hmac: fa253d3d5f3794b5c72da0ac2b4b4b6168e1ff1474a3ecb29c6b6b3a2f5a4413

...
