---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: install
  image: node:14-alpine
  commands: ["npm install"]

- name: standard
  image: node:14-alpine
  commands: ["npm run lint -s"]

- name: test-node-12
  image: node:12-alpine
  commands: ["npm run test:ci -s"]

- name: test-node-14
  image: node:14-alpine
  commands: ["npm run test:ci -s"]

- name: publish
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
---
kind: signature
hmac: 7a0c7709bef7a66034e10a4752e662f9d5c00075a2583636013896b93f9eb64f

...
