clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  install:
    group: pre
    image: node
    commands: ["npm install"]

  standard:
    group: test
    image: node
    commands: ["npm run lint -s"]

  test:
    group: test
    image: node
    commands: ["npm run test:ci -s"]

  publish:
    group: build
    image: marcbachmann/semantic-release:15.1.3
    secrets: [gh_token, npm_token]
